# Generated by Django 4.1.3 on 2024-08-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_remove_film_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='room',
            field=models.IntegerField(choices=[(1, 'Blue'), (2, 'Red'), (3, 'Green')], default=1, verbose_name='Room'),
        ),
    ]
